version: '3'
services:
  web:
    image: java_springv1_t6
    build: .
    ports:
      - "8196:8196"
    volumes:
      - persistent_volume:/app/volumes
    restart: unless-stopped
volumes:
  persistent_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/ubuntu/tri1/t6-breadbops/volumes
