name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/${{ secrets.USERNAME }}/tri2_t4_f1-backend_8102
            sudo docker-compose down
            cd volumes
            git checkout HEAD -- sqlite.db
            cd ..
            git pull
            sudo docker-compose up -d --build
