name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.KEY  }}
            HOST : ${{ secrets.HOST  }}
            USERNAME : ${{ secrets.USERNAME  }}
        run: |
            echo $PRIVATE_KEY | ssh -o StrictHostKeyChecking=no -i /dev/stdin ${USERNAME}@${HOST}
            cd /home/ubuntu/tri3/t3_8022_abopsc/
            sudo docker-compose down
            cd volumes
            git checkout HEAD -- sqlite.db
            cd ..
            git pull
            sudo docker-compose up -d --build
